FROM node:22-bookworm-slim

WORKDIR /app/packages/web

COPY packages/web/package.json /app/packages/web/package.json

RUN npm install --no-package-lock --no-fund --no-audit

COPY packages/web /app/packages/web

EXPOSE 3005

CMD ["npm", "run", "dev"]
